moudle: 
    train: !!bool True
---
dataload:
    max_frames: 400
    eval_frames: 300
    batch_size: 1000
    max_seg_per_spk: 500
    nDataLoaderThread: 8
    augment: False
    seed: 10
    sampler: False
---
train:
    test_interval: 5
    max_epoch: 100
    loss_moudle: "deep_embedding_loss"
    trainfunc: "AAMSoftmax"
---
optimizer:
    optimizer: "Adam"
    scheduler: "steplr"
    lr: 0.001
    lr_decay: 0.95
    weight_decay: 0
---
loss:
    hard_prob: 0.5
    hard_rand: 10
    margin: 0.1
    scale: 30
    nPerSpeaker: 1
    n_class: 1251
---
evaluation:
    dcf_p_target: 0.05
    dcf_c_miss: 1
    dcf_c_fa: 1
---
load_save:
    init_model: "I:\\paper2\\MAJOR\\CODES\\exps\\exp_Voxceleb_VGG_AAMSoftmax\\model\\model000000040.model"
    save_path: "exps\\exp_Voxceleb"
---
data:
    train_list: ".\\datas\\Vox1_train_list.txt"
    test_list: ".\\datas\\Voxceleb_test_sv_list.txt"
    test_si_list: ".\\datas\\Vox1_test_list.txt"
    musan_path: "I:\\datas\\Augments\\musan_split"
    rir_path: "I:\\datas\\Augments\\rirs_noises\\simulated_rirs"
---
model:
    n_mels: 80
    log_input: True
    model: "VGG"
    encoder_type: "SAP"
    n_out: 512



