data_list: ".\\datas\\Vox1_train_list.txt"
test_list: ".\\datas\\Vox1_test_list.txt"
test_sv_list: ".\\datas\\Voxceleb_test_sv_list.txt"
batch_size: 4
nDataLoaderThead: 0
max_epoch: 2
snr: 25
model_path: ".\\exps\\exp_Vox1"
lr: 0.001
lr_decay: 0.95
weight_decay: 0
test_interval: 1
threshold: -0.01
perb_thre: 9.4
A: 0.5
alpha: 12000
beta: 1200
features: 32
channels: 1
levels: 8
heads: 4
layers: 2
spr_name: ".\\features\\X_vector_speaker_features_Vox.npy"
avg_name: ".\\features\\X_vector_avg_feature_Vox.npy"
svmodel_path: "I:\\paper2\\MAJOR\\CODES\\exps\\exp_Voxceleb_ECAPA_TDNN_AAMSoftmax\\model\\model000000035.model"
tmodel_path: "I:\\paper2\\MAJOR\\CODES\\exps\\exp_Voxceleb_ECAPA_TDNN_AAMSoftmax\\model\\model000000035.model"
sapmodel_path: ".\\exps\\exp_Vox1\\sap000000001.model"
test_dataset: "..\\datas\\voxceleb1\\wav\\*\\*\\*.wav"
target_dataset: "/home/zhang/datas/vox1_test_wav/wav/id10281/*/*.wav"
rir_files: "I:\\datas\\Augments\\RIRS_NOISES\\simulated_rirs"
eval_frames: 300
tmodel: "ECAPA_TDNN"
model: "ECAPA_TDNN"
trainfunc: "AAMSoftmax"
nPerSpeaker: 1
n_out: 512
n_class: 1251
enroll: 25600
hidden_size: 128
dcf_p_target: 0.95
dcf_c_miss: 1
dcf_c_fa: 1
load_sap: False
train: True
is_targeted: True
is_randsample: True
zero_init: False