data_list: "./datas/Vox1_train_list.txt"
test_si_list: "./datas/Vox1_test_list.txt"
test_sv_list: "./datas/Voxceleb_test_sv_list.txt"
batch_size: 200
nDataLoaderThead: 0
max_epoch: 50
model_path: "./exps/exp_Vox1"
snr: 30
lr: 0.0001
lr_decay: 0.99
weight_decay: 0
test_interval: 1
threshold: -0.01
perb_thre: 9.4
A: 1
alpha: 12000
beta: 2000
heads: 4
layers: 2
spr_name: "./features/ECT_speaker_features_Vox.npy"
avg_name: "./features/ECT_avg_feature_Vox.npy"
svmodel_path: "./exps/exp_Vox1/ECT000000001.model"
tsvmodel_path: "./exps/exp_Vox1/ECT000000001.model"
sapmodel_path: "./exps/exp_Vox1/sap000000035.model"
test_dataset: "../datas/voxceleb1/wav/*/*/*.wav"
target_dataset: "/home/zhang/datas/vox1_test_wav/wav/id10281/*/*.wav"
eval_frames: 300
model: "ECAPA_TDNN" 
test_model: "ECAPA_TDNN"
trainfunc: "AAMSoftmax"
testfunc: "AAMSoftmax"
nPerSpeaker: 1
cat: 2
n_out: 512
n_class: 1211
enroll: 25600
hidden_size: 256
dcf_p_target: 0.95
dcf_c_miss: 1
dcf_c_fa: 1
load_sap: False
train: True
is_targeted: False
is_randsample: True
is_softmax_attack: False
adv_attack: 'sap'
moudle: 'sv'