moudle: 
    train: !!bool True
---
dataload:
    max_frames: 300
    eval_frames: 300
    batch_size: 200
    max_seg_per_spk: 500
    nDataLoaderThread: 0
    augment: False
    seed: 10
    sampler: False
---
train:
    test_interval: 2
    max_epoch: 50
    loss_moudle: "deep_embedding_loss"
    trainfunc: "AAMSoftmax"
---
optimizer:
    optimizer: "Adam"
    scheduler: "steplr"
    lr: 0.001
    lr_decay: 0.95
    weight_decay: 0
---
loss:
    hard_prob: 0.5
    hard_rand: 10
    margin: 0.1
    scale: 30
    nPerSpeaker: 1
    n_class: 251
---
evaluation:
    dcf_p_target: 0.05
    dcf_c_miss: 1
    dcf_c_fa: 1
---
load_save:
    init_model: ""
    save_path: "exps\\exp_LibriSpeech"
---
data:
    train_list: ".\\datas\\LibriSpeech_train_list.txt"
    test_list: ".\\datas\\LibriSpeech_test_list.txt"
    musan_path: "I:\\datas\\musan_split"
    rir_path: "I:\\datas\\rirs_noises\\simulated_rirs"
---
model:
    n_mels: 40
    log_input: True
    model: "ECAPA_TDNN"
    encoder_type: "SAP"
    n_out: 512



